version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: poc
      MYSQL_USER: admin-user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: on-failure:3
  app:
    build: .
    container_name: spring-boot-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/poc
      SPRING_DATASOURCE_USERNAME: admin-user
      SPRING_DATASOURCE_PASSWORD: password
    restart: on-failure:3
volumes:
  db-data:
